#!/bin/bash 

gcc -c src/configs/global.c -Iinclude -o bin/global.o
gcc -c src/configs/types.c -Iinclude -o bin/types.o
gcc -c src/inits/create_deck.c -Iinclude -o bin/create_deck.o
gcc -c src/inits/initialize_random.c -Iinclude -o bin/initialize_random.o
gcc -c src/mechanics/add_cards_to_other_player.c -Iinclude -o bin/add_cards_to_other_player.o
gcc -c src/mechanics/check_opponent_play.c -Iinclude -o bin/check_opponent_play.o
gcc -c src/mechanics/check_play.c -Iinclude -o bin/check_play.o
gcc -c src/mechanics/check_winner.c -Iinclude -o bin/check_winner.o
gcc -c src/mechanics/draw_card.c -Iinclude -o bin/draw_card.o
gcc -c src/mechanics/get_card_for_table.c -Iinclude -o bin/get_card_for_table.o
gcc -c src/mechanics/get_player_cards.c -Iinclude -o bin/get_player_cards.o
gcc -c src/mechanics/opponent_play.c -Iinclude -o bin/opponent_play.o
gcc -c src/mechanics/play_again_choose.c -Iinclude -o bin/play_again_choose.o
gcc -c src/mechanics/play_card.c -Iinclude -o bin/play_card.o
gcc -c src/mechanics/push_card.c -Iinclude -o bin/push_card.o
gcc -c src/mechanics/push_history.c -Iinclude -o bin/push_history.o
gcc -c src/mechanics/reverse_hands.c -Iinclude -o bin/reverse_hands.o
gcc -c src/prints/print_bold.c -Iinclude -o bin/print_bold.o
gcc -c src/prints/print_game.c -Iinclude -o bin/print_game.o
gcc -c src/prints/print_hands.c -Iinclude -o bin/print_hands.o
gcc -c src/prints/print_history.c -Iinclude -o bin/print_history.o
gcc -c src/prints/print_line_with_preffix.c -Iinclude -o bin/print_line_with_preffix.o
gcc -c src/prints/print_line.c -Iinclude -o bin/print_line.o
gcc -c src/prints/print_opponent_cards.c -Iinclude -o bin/print_opponent_cards.o
gcc -c src/prints/print_player_cards.c -Iinclude -o bin/print_player_cards.o
gcc -c src/prints/print_table.c -Iinclude -o bin/print_table.o
gcc -c src/prints/stylized_print.c -Iinclude -o bin/stylized_print.o
gcc -c src/screens/clear_screen.c -Iinclude -o bin/clear_screen.o
gcc -c src/screens/show_game_screen.c -Iinclude -o bin/show_game_screen.o
gcc -c src/screens/show_home_screen.c -Iinclude -o bin/show_home_screen.o
gcc -c src/screens/show_how_to_play_screen.c -Iinclude -o bin/show_how_to_play_screen.o
gcc -c src/screens/show_main_menu_screen.c -Iinclude -o bin/show_main_menu_screen.o
gcc -c src/screens/show_new_game_screen.c -Iinclude -o bin/show_new_game_screen.o
gcc -c src/screens/show_rules_screen.c -Iinclude -o bin/show_rules_screen.o
gcc -c src/screens/transition.c -Iinclude -o bin/transition.o
gcc -c src/tests/run_tests.c -Iinclude -o bin/run_tests.o
gcc -c src/tests/show_card_error_message.c -Iinclude -o bin/show_card_error_message.o
gcc -c src/tests/show_tests_error_message.c -Iinclude -o bin/show_tests_error_message.o
gcc -c src/updates/update_history.c -Iinclude -o bin/update_history.o
gcc -c src/updates/update_table.c -Iinclude -o bin/update_table.o
gcc -c src/utils/are_arrays_equal.c -Iinclude -o bin/are_arrays_equal.o
gcc -c src/utils/are_card_arrays_equal.c -Iinclude -o bin/are_card_arrays_equal.o
gcc -c src/utils/are_strings_equal.c -Iinclude -o bin/are_strings_equal.o
gcc -c src/utils/can_play_card.c -Iinclude -o bin/can_play_card.o
gcc -c src/utils/card_skip_next_player.c -Iinclude -o bin/card_skip_next_player.o
gcc -c src/utils/clear_input_buffer.c -Iinclude -o bin/clear_input_buffer.o
gcc -c src/utils/compaction.c  -Iinclude -o bin/compaction.o
gcc -c src/utils/compare_cards.c -Iinclude -o bin/compare_cards.o
gcc -c src/utils/concat_char.c -Iinclude -o bin/concat_char.o
gcc -c src/utils/concat_string.c -Iinclude -o bin/concat_string.o
gcc -c src/utils/copy_action.c -Iinclude -o bin/copy_action.o
gcc -c src/utils/count_digits.c -Iinclude -o bin/count_digits.o
gcc -c src/utils/delete_last_line.c -Iinclude -o bin/delete_last_line.o
gcc -c src/utils/delete_lines_by_errors.c -Iinclude -o bin/delete_lines_by_errors.o
gcc -c src/utils/get_color_ansi.c -Iinclude -o bin/get_color_ansi.o
gcc -c src/utils/get_color_name.c -Iinclude -o bin/get_color_name.o
gcc -c src/utils/handle_invalid_choice.c -Iinclude -o bin/handle_invalid_choice.o
gcc -c src/utils/int_between_parenthesis.c -Iinclude -o bin/int_between_barenthesis.o
gcc -c src/utils/int_to_string.c -Iinclude -o bin/int_to_string.o
gcc -c src/utils/is_action_match.c -Iinclude -o bin/is_action_match.o
gcc -c src/utils/is_color_match.c -Iinclude -o bin/is_color_match.o
gcc -c src/utils/is_colored_draw_card.c -Iinclude -o bin/is_colored_draw_card.o
gcc -c src/utils/is_in_interval.c -Iinclude -o bin/is_in_interval.o
gcc -c src/utils/is_invalid_color.c -Iinclude -o bin/is_invalid_color.o
gcc -c src/utils/is_normal_card.c -Iinclude -o bin/is_normal_card.o
gcc -c src/utils/is_number_match.c -Iinclude -o bin/is_number_match.o
gcc -c src/utils/is_wild_card.c -Iinclude -o bin/is_wild_card.o
gcc -c src/utils/random_array_index.c -Iinclude -o bin/random_array_index.o
gcc -c src/utils/reverse.c -Iinclude -o bin/reverse.o
gcc -c src/utils/sleep_time.c -Iinclude -o bin/sleep_time.o
gcc -c src/utils/sort_cards.c -Iinclude -o bin/sort_cards.o
gcc -c src/utils/str_compaction.c -Iinclude -o bin/str_compaction.o
gcc -c src/utils/swap.c -Iinclude -o bin/swap.o
gcc -c src/main.c -Iinclude -o bin/main.o

gcc bin/are_arrays_equal.o bin/are_card_arrays_equal.o bin/are_strings_equal.o bin/can_play_card.o bin/compaction.o bin/compare_cards.o bin/concat_char.o bin/concat_string.o bin/copy_action.o bin/count_digits.o bin/create_deck.o bin/get_card_for_table.o bin/get_color_ansi.o bin/get_color_name.o bin/global.o bin/int_between_barenthesis.o bin/int_to_string.o bin/is_action_match.o bin/is_color_match.o bin/is_in_interval.o bin/is_invalid_color.o bin/is_normal_card.o bin/is_number_match.o bin/is_wild_card.o bin/main.o bin/push_card.o bin/push_history.o bin/random_array_index.o bin/reverse.o bin/run_tests.o bin/show_card_error_message.o bin/show_tests_error_message.o bin/sort_cards.o bin/str_compaction.o bin/swap.o bin/types.o bin/clear_screen.o bin/show_home_screen.o bin/show_main_menu_screen.o bin/sleep_time.o bin/transition.o bin/get_player_cards.o bin/print_game.o bin/print_hands.o bin/print_history.o bin/print_line_with_preffix.o bin/print_line.o bin/print_opponent_cards.o bin/print_player_cards.o bin/print_table.o bin/show_new_game_screen.o bin/clear_input_buffer.o bin/play_card.o bin/show_game_screen.o bin/add_cards_to_other_player.o bin/check_opponent_play.o bin/check_play.o bin/check_winner.o bin/draw_card.o bin/opponent_play.o bin/play_again_choose.o bin/reverse_hands.o bin/update_history.o bin/update_table.o bin/card_skip_next_player.o bin/delete_last_line.o bin/delete_lines_by_errors.o bin/handle_invalid_choice.o bin/is_colored_draw_card.o bin/show_rules_screen.o bin/print_bold.o bin/stylized_print.o bin/initialize_random.o bin/show_how_to_play_screen.o -o bin/exec